export const games = [
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'wall', 0, 0, 0, 0],
            ['pawn2', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'wall', 0, 0, 0, 0],
            ['rook', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'wall', 0, 0, 0, 0],
            ['wall','wall', 0, 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ['wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 0, 'wall', 'wall', 'wall'],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ['enemy', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ['wall', 'wall', 0, 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall']
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        message: 'custom level',
        level: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
    }
]
