export const games = [
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['pawn'], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['rook'], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['enemy'], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0]],
            [[0], [0], ['knight'], [0], [0]],
            [[0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], []],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], ['enemy'], [], []]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0]],
            [['wall'], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall'], [0], [0]],
            [[], [], [], ['wall'], [], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0]],
            [[], [], ['wall'], ['wall'], [], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], ['wall']],
            [[], [], [], ['wall'], [], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0]],
            [['wall'], [], [], ['wall'], [], [], [], [], [], [], [], ['wall'], ['wall'], [], []],
            [[], [], ['queen'], ['wall'], [], [], [], [], [], [], [], ['wall'], [], ['enemy'], []]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['rook'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['enemy']],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall']],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall']],
            [['king'], [], [], [], [], [], [], [], [0], [0], ['wall'], ['wall'], ['wall']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], ['wall'], [], ['wall'], [], [], [], [], [], []],
            [[], [], [], [], ['wall'], ['wall'], ['wall'], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [['wall'], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0], ['wall'], [0], [0], [0], ['wall'], [0], [0]],
            [['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0]],
            [['wall'], [0], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], [0], [0], [0], ['wall']],
            [[0], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0], [0], ['wall'], [0]],
            [[0], ['wall'], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], ['wall'], [0], [0], [0], [0], [0]],
            [[], ['wall'], [], ['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], [], [], [], [], []],
            [['wall'], ['wall'], ['wall'], ['wall'], [], [], ['wall'], ['bishop'], ['wall'], [], ['wall'], [], [], ['wall'], []],
            [[], [], [], [], [], [], [], ['wall'], [], ['wall'], [], [], [], ['wall'], []],
            [['wall'], ['wall'], ['wall'], [], [], [], [], [0], ['wall'], [], ['wall'], [], ['wall'], ['wall'], []],
            [[], [], ['wall'], ['wall'], [], [], [], ['wall'], [], ['wall'], [], ['wall'], ['wall'], [], ['wall']],
            [[], [], [], ['wall'], ['wall'], [], [], [], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], []],
            [[0], ['wall'], [], [], ['wall'], ['wall'], [], ['wall'], [], ['wall'], ['enemy'], [], [], ['wall'], []],
            [[], ['wall'], [], [], [], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], [], [], [], ['wall']],
            [[], ['wall'], [], [], [], [], [], ['wall'], ['wall'], [], [], [], [], ['wall'], ['wall']],
            [['wall'], ['wall'], ['wall'], [], [], [], [], ['wall'], [], [], [], [], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], ['enemy']],
            [[0], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall']],
            [['knight'], [0], [0], ['wall'], [0], [0], [0], ['wall'], ['wall'], ['wall']],
            [['king'], [0], [0], ['wall'], [0], [0], ['wall'], ['wall'], ['wall'], ['wall']],
            [['bishop'], ['wall'], [0], ['wall'], [0], [0], ['wall'], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['enemy'], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], ['knight'], [0], [0]],
            [['wall'], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [[0], [0], ['wall'], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['knight'], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], ['wall'], [0], [0], ['wall'], [0], [0], [0], [0], [0]]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['king']],
            [['pedestal'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['wall']],
            [['pedestal'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0]],
            [['pawn2'], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall'], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], ['wall'], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall']],
            [['wall'], [], [], [], [], [0], [0], [0], ['wall'], [0], [0]],
            [['enemy'], [], [], [], [], ['wall'], [], [0], ['wall'], ['wall'], []],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], ['wall'], ['wall'], [0], [0], ['wall'], ['enemy'], ['wall'], ['queen'], ['wall'], ['wall'], ['wall'], ['queen'], ['wall']],
            [[0], [0], [0], [0], ['wall'], [0], ['wall'], ['wall'], ['pedestal'], ['wall'], ['queen'], ['queen'], ['queen'], ['wall'], ['queen'], ['wall']],
            [[0], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall'], ['queen'], ['wall'], ['wall'], ['wall'], ['queen'], ['wall']],
            [[0], [0], ['pedestal'], [0], ['wall'], [0], [0], ['wall'], [0], ['wall'], ['queen'], ['wall'], ['queen'], ['wall'], ['queen'], ['wall']],
            [['pedestal', 'rook'], ['pedestal'], ['pedestal'], [0], ['wall'], ['wall'], [0], ['wall'], [0], ['wall'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['wall']],
            [[], [], ['pedestal'], [], [], [0], ['pedestal'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], [], [], [], [], [], [], [], [0], ['bishop'], [0], [0]],
            [[], [], [], [], [0], [], [], ['wall'], ['wall'], ['wall'], [], [], [0], [0], [0], [0]],
            [[], [0], [0], [], [0], [], [], ['wall'], [], ['wall'], [], [], [0], [0], [0], [0]],
            [[], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], ['bishop'], [0], [], [], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], [], [], ['wall'], ['king'], ['wall'], [], [], [0], [0], [0], ['pedestal']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [], [], [0], [], [0], [], [], [], [], []],
            [[], [], [], [], [], [], [], [0], [], [0], [], [], [], [], []],
            [[], [], [], [], [], [], [], ['bishop'], [], [0], [], [], [], [], []],
            [[], [], [], [], [], [], [], ['bishop'], [], [0], [], [], [], [], []],
            [['wall'], ['wall'], ['wall'], ['wall'], [], [], [], ['king'], [], [0], [], ['wall'], ['wall'], ['wall'], ['wall']],
            [['enemy'], [], [], [], [], [], [], ['bishop'], [], [0], [], [], [], [], ['enemy']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [], [], ['bishop'], [], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], ['wall'], [], [], ['bishop'], [], [0], ['wall'], [], [], [], []],
            [[], [], [], [], ['wall'], [], [], ['bishop'], [], [0], ['wall'], [], [], [], []],
            [[], [], [], [], ['wall'], [], [], ['bishop'], [], [0], ['wall'], [], [], [], []],
            [[], [], [], [], ['wall'], [0], [], ['bishop'], [], [0], ['wall'], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[0], ['wall'], [], [], [], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], ['enemy'], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], ['wall'], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], [], [0], ['wall'], ['wall'], [0]],
            [[0], ['wall'], ['wall'], [], [], [0], [0], ['wall'], [0]],
            [[], ['wall'], [], [], [], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], [], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [0], ['knight'], [], [], ['wall'], []],
            [[0], ['wall'], [], ['knight'], ['knight'], ['knight'], [], ['wall'], []],
            [[], ['wall'], ['knight'], ['knight'], ['knight'], ['knight'], ['knight'], ['wall'], []],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [], [], [], [], [], []],
            [[0], [], [], [], [], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], []],
            [['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen']],
            [['queen'], ['wall'], ['wall'], ['wall'], ['queen'], ['wall'], ['wall'], ['queen'], ['queen'], ['wall'], ['queen']],
            [['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen']],
            [['queen'], ['pedestal', 'queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['wall'], ['queen'], ['queen']],
            [['pedestal', 'queen'], ['queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['queen'], ['wall'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen']],
            [['pedestal', 'queen'], ['wall'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['wall'], ['queen'], ['queen'], ['wall'], ['queen'], ['queen'], ['queen']],
            [['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['queen'], ['wall'], ['queen'], ['wall'], ['wall'], ['wall']],
            [['knight'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['wall'], ['enemy']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [],
    },
    {
        message: 'custom level',
        level:  [
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]]
        ]
    }
]
