export const games = [
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['pawn'], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['rook'], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['enemy'], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0]],
            [[0], [0], ['knight'], [0], [0]],
            [[0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], []],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], ['enemy'], [], []]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0]],
            [['wall'], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall'], [0], [0]],
            [[], [], [], ['wall'], [], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0]],
            [[], [], ['wall'], ['wall'], [], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], ['wall']],
            [[], [], [], ['wall'], [], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0]],
            [['wall'], [], [], ['wall'], [], [], [], [], [], [], [], ['wall'], ['wall'], [], []],
            [[], [], ['queen'], ['wall'], [], [], [], [], [], [], [], ['wall'], [], ['enemy'], []]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['rook'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['enemy']],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall']],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall']],
            [['king'], [], [], [], [], [], [], [], [0], [0], ['wall'], ['wall'], ['wall']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], ['wall'], [], ['wall'], [], [], [], [], [], []],
            [[], [], [], [], ['wall'], ['wall'], ['wall'], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: false,
        leastMove: 0,
        coin: 10,
        level:  [
            [['wall'], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0], ['wall'], [0], [0], [0], ['wall'], [0], [0]],
            [['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0]],
            [['wall'], [0], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], [0], [0], [0], ['wall']],
            [[0], [0], ['wall'], ['wall'], [0], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [0], [0], ['wall'], [0]],
            [[0], ['wall'], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], ['wall'], [0], [0], [0], [0], [0]],
            [[], ['wall'], [], ['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], [], [], [], [], []],
            [['wall'], ['wall'], ['wall'], ['wall'], [], [], ['wall'], ['bishop'], ['wall'], [], ['wall'], [], [], ['wall'], []],
            [[], [], [], [], [], [], [], ['wall'], [], ['wall'], [], [], [], ['wall'], []],
            [['wall'], ['wall'], ['wall'], [], [], [], [], [0], ['wall'], [], ['wall'], [], ['wall'], ['wall'], []],
            [[], [], ['wall'], ['wall'], [], [], [], ['wall'], [], ['wall'], [], ['wall'], ['wall'], [], ['wall']],
            [[], [], [], ['wall'], ['wall'], [], [], [], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], []],
            [[0], ['wall'], [], [], ['wall'], ['wall'], [], ['wall'], [], ['wall'], ['enemy'], [], [], ['wall'], []],
            [[], ['wall'], [], [], [], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], [], [], [], ['wall']],
            [[], ['wall'], [], [], [], [], [], ['wall'], ['wall'], [], [], [], [], ['wall'], ['wall']],
            [['wall'], ['wall'], ['wall'], [], [], [], [], ['wall'], [], [], [], [], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], ['enemy']],
            [[0], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall']],
            [['knight'], [0], [0], ['wall'], [0], [0], [0], ['wall'], ['wall'], ['wall']],
            [['king'], [0], [0], ['wall'], [0], [0], ['wall'], ['wall'], ['wall'], ['wall']],
            [['bishop'], ['wall'], [0], ['wall'], [0], [0], ['wall'], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['enemy'], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], ['knight'], [0], [0]],
            [['wall'], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [[0], [0], ['wall'], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['knight'], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], ['wall'], [0], [0], ['wall'], [0], [0], [0], [0], [0]]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['king']],
            [['pedestal'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['wall']],
            [['pedestal'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], [0]],
            [['pawn2'], [0], [0], [0], [0], [0], [0], [0], ['wall'], ['wall'], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], ['wall'], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall']],
            [['wall'], [], [], [], [], [0], [0], [0], ['wall'], [0], [0]],
            [['enemy'], [], [], [], [], ['wall'], [], [0], ['wall'], ['wall'], []],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], ['wall'], ['wall'], [0], [0], ['wall'], ['enemy'], ['wall'], ['queen'], ['wall'], ['wall'], ['wall'], ['queen'], ['wall']],
            [[0], [0], [0], [0], ['wall'], [0], ['wall'], ['wall'], ['pedestal'], ['wall'], ['queen'], ['queen'], ['queen'], ['wall'], ['queen'], ['wall']],
            [[0], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall'], ['queen'], ['wall'], ['wall'], ['wall'], ['queen'], ['wall']],
            [[0], [0], ['pedestal'], [0], ['wall'], [0], [0], ['wall'], [0], ['wall'], ['queen'], ['wall'], ['queen'], ['wall'], ['queen'], ['wall']],
            [['pedestal', 'rook'], ['pedestal'], ['pedestal'], [0], ['wall'], ['wall'], [0], ['wall'], [0], ['wall'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['wall']],
            [[], [], ['pedestal'], [], [], [0], ['pedestal'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], [], [], [], [], [], [], [], [0], ['bishop'], [0], [0]],
            [[], [], [], [], [0], [], [], ['wall'], ['wall'], ['wall'], [], [], [0], [0], [0], [0]],
            [[], [0], [0], [], [0], [], [], ['wall'], [], ['wall'], [], [], [0], [0], [0], [0]],
            [[], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], ['bishop'], [0], [], [], [0], [0], [0], [0]],
            [[], [], [], [], ['wall'], [], [], ['wall'], ['king'], ['wall'], [], [], [0], [0], [0], ['pedestal']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [], [], [0], [], [0], [], [], [], [], []],
            [[], [], [], [], [], [], [], [0], [], [0], [], [], [], [], []],
            [[], [], [], [], [], [], [], ['bishop'], [], [0], [], [], [], [], []],
            [[], [], [], [], [], [], [], ['bishop'], [], [0], [], [], [], [], []],
            [['wall'], ['wall'], ['wall'], ['wall'], [], [], [], ['king'], [], [0], [], ['wall'], ['wall'], ['wall'], ['wall']],
            [['enemy'], [], [], [], [], [], [], ['bishop'], [], [0], [], [], [], [], ['enemy']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [], [], ['bishop'], [], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], ['wall'], [], [], ['bishop'], [], [0], ['wall'], [], [], [], []],
            [[], [], [], [], ['wall'], [], [], ['bishop'], [], [0], ['wall'], [], [], [], []],
            [[], [], [], [], ['wall'], [], [], ['bishop'], [], [0], ['wall'], [], [], [], []],
            [[], [], [], [], ['wall'], [0], [], ['bishop'], [], [0], ['wall'], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[0], ['wall'], [], [], [], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], ['enemy'], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], ['wall'], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], [], [0], ['wall'], ['wall'], [0]],
            [[0], ['wall'], ['wall'], [], [], [0], [0], ['wall'], [0]],
            [[], ['wall'], [], [], [], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [], [], [0], [0], ['wall'], [0]],
            [[0], ['wall'], [], [0], ['knight'], [], [], ['wall'], []],
            [[0], ['wall'], [], ['knight'], ['knight'], ['knight'], [], ['wall'], []],
            [[], ['wall'], ['knight'], ['knight'], ['knight'], ['knight'], ['knight'], ['wall'], []],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [], [], [], [], [], []],
            [[0], [], [], [], [], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], []],
            [['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen']],
            [['queen'], ['wall'], ['wall'], ['wall'], ['queen'], ['wall'], ['wall'], ['queen'], ['queen'], ['wall'], ['queen']],
            [['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen']],
            [['queen'], ['pedestal', 'queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['wall'], ['queen'], ['queen']],
            [['pedestal', 'queen'], ['queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['queen'], ['wall'], ['queen'], ['queen'], ['queen'], ['queen'], ['queen']],
            [['pedestal', 'queen'], ['wall'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['wall'], ['queen'], ['queen'], ['wall'], ['queen'], ['queen'], ['queen']],
            [['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['queen'], ['wall'], ['queen'], ['wall'], ['wall'], ['wall']],
            [['knight'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['pedestal', 'queen'], ['queen'], ['queen'], ['queen'], ['queen'], ['wall'], ['enemy']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], ['wall'], ['key'], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['pedestal'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['pedestal'], [0], [0], ['wall'], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['pawn2'], [0], [0], ['wall'], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['wall'], [0], [0], [0], [0], ['wall'], [0], [0], [0], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], ['pawn2'], [0], [0], ['wall'], ['lockblock'], ['lockblock'], ['lockblock']],
            [[], [], [], [], [], ['pawn2'], [0], [0], ['wall'], ['lockblock'], [0], [0]],
            [[], [], [], [], [], ['pawn2'], [0], [0], ['wall'], ['lockblock'], [0], ['enemy']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        limit: 65,
        coin: 10,
        level:  [
            [['enemy'], ['enemy'], ['enemy'], ['enemy'], ['enemy'], ['enemy'], ['enemy'], ['enemy']],
            [['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']],
            [['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']],
            [['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']],
            [['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']],
            [['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']],
            [['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']],
            [['pedestal', 'knight'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy'], ['pedestal', 'enemy']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [['key'], ['key'], [0], [0], ['key'], ['key'], ['key'], ['key'], ['key'], ['key'], [0], ['key']],
            [[], [], [], [], [], [], [], [], [0], ['lockblock'], ['lockblock'], ['lockblock']],
            [[], [], [], [], [], [], [], [], [0], ['lockblock'], [0], ['lockblock']],
            [[], [], [], [], [], [], ['wall'], [], [0], ['lockblock'], ['king'], ['lockblock']],
            [[], [], [], [], [], [0], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall']],
            [['wall'], [], [], [], ['wall'], [], ['wall'], [], [0], [0], [0], [0]],
            [['wall'], ['pedestal'], ['pedestal'], ['pedestal'], ['wall'], ['pedestal'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [['wall'], [], [], [], ['wall'], [0], [0], [0], ['wall'], ['knight'], ['wall'], ['enemy']],
            [['wall'], [], [], [], ['wall'], ['pedestal'], [], [], ['wall'], ['wall'], ['wall'], ['pedestal']],
            [['wall'], ['pedestal'], ['pedestal'], ['pedestal'], ['wall'], [], [], [0], [0], ['wall'], ['wall'], ['pedestal']],
            [['wall'], [0], [0], [0], ['wall'], [], [], [0], [0], [], [], ['wall']],
            [['wall'], ['bishop'], [], [], ['wall'], [0], [0], [0], [0], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [['enemy'], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0]],
            [[0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0]],
            [['pedestal'], [], [], [], [], [0]],
            [['bishop'], ['knight'], ['rook'], ['king'], ['queen'], ['pawn2']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [['wall'], ['wall'], ['wall'], ['king'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall']],
            [['wall'], ['wall'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall']],
            [['wall'], ['wall'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['wall']],
            [['wall'], ['wall'], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], ['enemy'], ['wall']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall']],
            [['wall'], [], [], [], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], [0], [0], [0]],
            [['wall'], [], [], [], ['wall'], ['wall'], [0], ['wall'], [0], ['wall'], [0], ['wall'], ['wall'], [0], [0], [0]],
            [['wall'], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], [], ['pedestal'], [], ['wall'], [0], [0], [0], [0], [0], [0], [0], ['wall'], [0], ['pedestal'], [0]],
            [['wall'], [], [], [], [], ['wall'], [0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0]],
            [['wall'], [0], [0], [0], [0], [0], [0], ['rook'], [0], ['queen'], [0], [0], [0], [0], [0], [0]]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []],
            [['rook'], ['triggerblock'], [], ['untriggerblock'], [], ['triggerblock'], [], ['untriggerblock'], [], ['triggerblock'], [], ['untriggerblock'], [], ['triggerblock'], [], ['enemy']],
            [['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [0], ['wall'], [0], ['wall'], [], ['wall'], ['wall']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], ['wall'], [], [], [], [], [], [], [], [], [], [], [], [], [], []],
            [[0], ['wall'], [0], [], [], [], [], [], [], [], [], [], [], [], [], []],
            [[0], ['wall'], ['wall'], [0], ['wall'], [0], [], [], [], [], [], [], [], [], [], []],
            [['pad'], ['wall'], [0], [], [], [0], [0], [], [], [], [], [], [], [], [], []],
            [['wall'], ['wall'], [0], [0], [0], ['wall'], [], [0], [0], [], [], [], [], [], [], []],
            [[0], [], [0], [0], [0], [], [], [0], [], [], [], [], [], [], [], []],
            [[], [], ['knight'], [], ['wall'], [], [], [], [], [], [], [], [], [], [], []]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [['wall'], ['wall'], ['key'], [], [], [], ['wall'], ['wall'], [], [0], [0], [0], [0], [0]],
            [[], [], ['wall'], ['wall'], ['wall'], [0], ['wall'], ['wall'], ['pawn2'], [0], [0], [0], ['wall'], [0]],
            [[], [], [], [], [], [0], ['wall'], ['wall'], ['wall'], [0], [0], [0], ['wall'], [0]],
            [['wall'], ['wall'], ['wall'], [0], ['wall'], ['wall'], ['wall'], ['wall'], [], [0], [0], ['wall'], ['wall'], [0]],
            [[], [], [], [], [], [], ['wall'], ['wall'], [], [0], ['wall'], ['wall'], ['wall'], [0]],
            [['bishop'], [], [], [0], [0], [0], ['wall'], ['wall'], [0], [0], [0], [0], ['wall'], ['key']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], ['key'], ['wall'], ['wall'], [], [0], [0], [0], ['wall'], [0]],
            [[0], [], [], [], [0], [], ['wall'], ['wall'], [], [0], [0], [0], ['wall'], [0]],
            [[0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [], [], [0], [0], ['wall'], [0]],
            [[], [], [], [0], [0], [], ['wall'], ['wall'], ['rook'], [], [0], [0], ['wall'], ['lockblock']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['lockblock'], ['lockblock'], ['lockblock'], ['lockblock'], ['lockblock'], ['lockblock']],
            [['knight'], [], [], [], [], [], ['wall'], ['wall'], [], [], [], ['wall'], ['lockblock'], ['enemy']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [['queen'], [0], [0], [0], ['teleport'], ['wall'], [0], [0], [0], [0], [0], [0], ['wall'], ['teleport']],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0], [0], [0], [0], ['wall'], [0]],
            [[0], [0], [0], [0], [0], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0]],
            [[0], [0], [0], [0], [0], ['wall'], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], ['wall'], ['teleport'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [[], [], [], [], [], ['wall'], [0], ['wall'], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']],
            [['teleport'], [], [], [], [], [0], [0], [0], [0], [0], [0], [0], [0], ['enemy']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0], [0], [0]],
            [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]],
            [['wall'], ['wall'], [], [], [], [0], [0], ['wall'], ['wall'], [0], [0], [0]],
            [[], ['wall'], [], [], [], [0], [0], ['wall'], [0], [0], [0], [0]],
            [[], ['wall'], [], [], [], [0], [0], ['wall'], [0], [0], [0], [0]],
            [[], ['wall'], [], [], [], [], [0], ['wall'], [0], [0], [0], [0]],
            [[], ['wall'], ['bishop'], ['bishop'], ['bishop'], ['bishop'], ['bishop'], ['wall'], [0], [0], [0], [0]],
            [[], ['wall'], ['bishop'], ['bishop'], ['bishop'], ['bishop'], ['bishop'], ['wall'], [0], [0], [0], [0]],
            [[], ['wall'], ['bishop'], ['bishop'], ['bishop'], ['bishop'], ['bishop'], ['wall'], [0], [0], [0], [0]],
            [[], ['wall'], ['bishop'], ['bishop'], ['king'], ['bishop'], ['bishop'], ['wall'], [0], ['enemy'], [0], [0]]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], [], [], [], [], [], [], [], [], [], []],
            [['pedestal', 'rook'], ['wall'], [0], [0], [0], [0], [0], [0], [0], [0], ['pedestal'], []],
            [['pedestal'], ['wall'], [], [], [], [], [], [], [], [], [], []],
            [['pawn2'], ['wall'], [], [], [], [], [], [], [], [], [], []],
            [['wall'], ['wall'], [], [], [], [], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], [], []],
            [[], [], [], [], [], [], [], [], [], [], [], []],
            [['wall'], ['wall'], [], [], [], [], [], [], [], [], [], []],
            [['wall'], ['wall'], [], [], [], [], [], [], [], [], [], []],
            [['enemy'], ['lockblock'], ['key'], [], ['key'], [], ['key'], [], ['key'], [], ['key'], []],
            [['wall'], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall']],
            [['wall'], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall']],
            [['wall'], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], ['wall'], [], [], ['key'], ['wall'], ['lockblock'], ['wall'], ['wall'], ['lockblock'], ['wall'], [0], [0], ['triggerblock'], [0]],
            [['pedestal'], ['pedestal'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['pedestal'], ['wall'], ['wall'], ['pedestal'], ['wall'], ['wall'], [0], ['pedestal'], [0]],
            [['pawn2'], ['pawn2'], ['wall'], [], [], ['wall'], [], ['pawn2'], ['wall'], ['wall'], ['pawn2'], ['wall'], [0], [0], ['pawn2'], [0]],
            [['pedestal'], ['pedestal'], [], ['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['pedestal'], ['wall'], [0], [0], ['wall'], [0]],
            [[], [0], [0], ['wall'], ['wall'], ['wall'], [0], [0], ['wall'], ['wall'], [], ['wall'], ['wall'], [0], ['wall'], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], [0], ['wall'], [0], [], ['wall'], [], [], [], ['wall'], ['enemy'], ['wall'], [0]],
            [[0], [0], [0], ['wall'], ['wall'], ['wall'], [], [], ['wall'], ['wall'], [], ['wall'], ['wall'], ['wall'], [0], [0]],
            [[], [], [], ['wall'], [0], [0], [], [], [], [], [], [], ['wall'], ['wall'], ['wall'], [0]],
            [[], ['pad'], [0], ['wall'], [0], [0], [], [], [], [], [], [], ['wall'], ['wall'], ['wall'], [0]],
            [['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [[], [], ['teleport'], [], ['teleport'], [], ['teleport'], [], ['teleport'], [], ['wall'], [], [0]],
            [[], [], [], [], [], [], [], [], [], [], ['wall'], [], [0]],
            [[], [], [], [], [], [], [], [], ['wall'], [], ['wall'], [], [0]],
            [[], [], [], [], [], [], [], [], ['wall'], [], ['wall'], [], [0]],
            [[], [], [], [], [], [], ['wall'], [], ['wall'], [], ['wall'], [], [0]],
            [[], [], [], [], [], [], ['wall'], [], ['wall'], [], ['wall'], [], [0]],
            [[], [], [], [], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], [], [0]],
            [[], [], [], [], ['wall'], [], ['wall'], ['teleport'], ['wall'], [], ['wall'], [], [0]],
            [['knight'], [], ['wall'], [], ['wall'], ['teleport'], ['wall'], [], ['wall'], [], ['wall'], [], [0]],
            [['knight'], [], ['wall'], ['teleport'], ['wall'], [], ['wall'], [], ['wall'], [], ['wall'], ['enemy'], [0]]
            ],
    },
    {
        isDone: false,
        isLock: true,
        leastMove: 0,
        coin: 10,
        level:  [
            [['teleport'], ['knight'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock']],
            [['triggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock']],
            [['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock']],
            [['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock']],
            [['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['lockblock'], ['lockblock']],
            [['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['triggerblock'], ['lockblock'], ['key']],
            [['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['wall'], ['wall'], ['wall'], ['wall']],
            [['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['triggerblock'], ['untriggerblock'], ['untriggerblock'], ['untriggerblock'], ['wall'], ['wall'], ['wall'], ['wall']],
            [['wall'], ['wall'], ['triggerblock'], ['triggerblock'], ['triggerblock'], ['triggerblock'], ['triggerblock'], ['wall'], ['wall'], ['enemy'], ['wall']],
            [['wall'], ['wall'], ['wall'], ['untriggerblock'], ['untriggerblock'], ['untriggerblock'], ['untriggerblock'], ['wall'], ['lockblock'], ['wall'], ['wall']],
            [['teleport'], ['pad'], ['wall'], ['wall'], [0], [0], [0], [0], ['wall'], ['wall'], ['wall']],
            [['queen'], ['wall'], ['wall'], ['wall'], ['wall'], ['pad'], ['wall'], ['pad'], ['wall'], ['wall'], ['wall']]
            ],
    },
    {
        message: 'custom level',
        level:  [
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]],
            [[0],[0],[0],[0],[0]]
        ]
    }
]
